USE master
GO
IF EXISTS (SELECT 1 FROM sys.databases WHERE [name] = N'TaskDb')
BEGIN
    ALTER DATABASE TaskDb SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE TaskDb;
END;
GO
CREATE DATABASE TaskDb
GO
USE TaskDb
GO


CREATE TABLE Student 
(
    StudentId INTEGER PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL
);

CREATE TABLE Task 
(
    TaskId INTEGER PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Description VARCHAR(100) NOT NULL,
    DueDate DATE NOT NULL,
    StudentId INTEGER NOT NULL,
    FOREIGN KEY (StudentId) REFERENCES Student (StudentId)
);

CREATE TABLE Professor 
(
    ProfessorId INTEGER PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL
);

CREATE TABLE TaskRating 
(
    TaskId INTEGER NOT NULL,
    Rating INTEGER NOT NULL,
    ProfessorId INTEGER NOT NULL,
    UNIQUE (TaskId, ProfessorId),
    FOREIGN KEY (TaskId) REFERENCES Task (TaskId),
    FOREIGN KEY (ProfessorId) REFERENCES Professor (ProfessorId)
);